-- Generated by hyprconf2lua v1.3.2
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- --- Forest Theme ---

hl.config({
    general = {
        gaps_in = 6,
        gaps_out = 12,
        border_size = 2,
        col = {
            active_border = { colors = { "rgba(7ab648ee)", "rgba(c8a84bee)" }, angle = 45 },
            inactive_border = "rgba(2e3d2888)",
        },
    },
})

hl.config({
    decoration = {
        rounding = 8,
        blur = {
            enabled = true,
            size = 6,
            passes = 2,
            new_optimizations = true,
        },
        shadow = {
            enabled = true,
            range = 12,
            render_power = 3,
            color = "rgba(0d1a0bee)",
        },
    },
})

hl.config({
    animations = {
        enabled = true,
    },
})

hl.curve("forest", {
    type = "bezier",
    points = { { 0.25, 0.46 }, { 0.45, 0.94 } },
})

hl.animation({ leaf = "windows",     enabled = true, speed = 5,  bezier = "forest" })
hl.animation({ leaf = "windowsOut",  enabled = true, speed = 5,  bezier = "default", style = "popin 80%" })
hl.animation({ leaf = "border",      enabled = true, speed = 8,  bezier = "default" })
hl.animation({ leaf = "fade",        enabled = true, speed = 5,  bezier = "default" })
hl.animation({ leaf = "workspaces",  enabled = true, speed = 4,  bezier = "default" })
