-- Generated by hyprconf2lua v1.3.2
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- --- Glass Theme ---

-- Blur waybar layer surface (replaces deprecated blurls directive)
hl.layer_rule({
    match = { namespace = "waybar" },
    blur = true,
})

hl.config({
    general = {
        gaps_in = 8,
        gaps_out = 15,
        border_size = 2,
        col = {
            active_border = { colors = { "rgba(8833ffee)", "rgba(ff00ffee)" }, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },
    },
})

hl.config({
    decoration = {
        rounding = 12,
        blur = {
            enabled = true,
            size = 8,
            passes = 3,
            new_optimizations = true,
            ignore_opacity = true,
        },
        shadow = {
            enabled = true,
            range = 15,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
    },
})

hl.config({
    animations = {
        enabled = true,
    },
})

hl.curve("myBezier", {
    type = "bezier",
    points = { { 0.05, 0.9 }, { 0.1, 1.05 } },
})

hl.animation({ leaf = "windows",     enabled = true, speed = 7,  bezier = "myBezier" })
hl.animation({ leaf = "windowsOut",  enabled = true, speed = 7,  bezier = "myBezier", style = "popin 80%" })
hl.animation({ leaf = "border",      enabled = true, speed = 10, bezier = "myBezier" })
hl.animation({ leaf = "fade",        enabled = true, speed = 7,  bezier = "myBezier" })
hl.animation({ leaf = "workspaces",  enabled = true, speed = 6,  bezier = "myBezier" })

-- Per-app opacity so compositor blur bleeds through (blur is globally on; opacity creates the transparency)
hl.window_rule({ match = { class = "^vesktop$" }, opacity = "0.92 override" })
hl.window_rule({ match = { class = "^zen$" },     opacity = "0.92 override" })
-- real wm_class is "Spotify" (capital S)
hl.window_rule({ match = { class = "^Spotify$" }, opacity = "0.92 override" })
-- Steam shell only; steam_app_ games excluded to avoid gameplay interference
hl.window_rule({ match = { class = "^steam$" },   opacity = "0.88 override" })
