[global]
    frame_color = "#ca9ee6"

[urgency_low]
    background = "#303446"
    foreground = "#737994"
    frame_color = "#414559"
    timeout = 8

[urgency_normal]
    background = "#303446"
    foreground = "#c6d0f5"
    frame_color = "#ca9ee6"
    timeout = 10

[urgency_critical]
    background = "#e78284"
    foreground = "#303446"
    frame_color = "#e78284"
    timeout = 0
