-- Generated by hyprconf2lua v1.3.2
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- --- Catppuccin Frappé Theme ---

hl.config({
    general = {
        gaps_in = 6,
        gaps_out = 12,
        border_size = 2,
        col = {
            active_border = { colors = { "rgba(ca9ee6ee)", "rgba(8caaeeee)" }, angle = 45 },
            inactive_border = "rgba(414559aa)",
        },
    },
})

hl.config({
    decoration = {
        rounding = 10,
        blur = {
            enabled = true,
            size = 6,
            passes = 2,
            new_optimizations = true,
        },
        shadow = {
            enabled = true,
            range = 12,
            render_power = 3,
            color = "rgba(303446ee)",
        },
    },
})

hl.config({
    animations = {
        enabled = true,
    },
})

hl.curve("catppuccin", {
    type = "bezier",
    points = { { 0.05, 0.9 }, { 0.1, 1.05 } },
})

hl.animation({ leaf = "windows",     enabled = true, speed = 6,  bezier = "catppuccin" })
hl.animation({ leaf = "windowsOut",  enabled = true, speed = 6,  bezier = "catppuccin", style = "popin 80%" })
hl.animation({ leaf = "border",      enabled = true, speed = 8,  bezier = "catppuccin" })
hl.animation({ leaf = "fade",        enabled = true, speed = 6,  bezier = "catppuccin" })
hl.animation({ leaf = "workspaces",  enabled = true, speed = 5,  bezier = "catppuccin" })
