-- Generated by hyprconf2lua v1.3.2
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- --- Modular Theme Loading ---

dofile(os.getenv("HOME") .. "/.config/hypr/themes/current/hypr.lua")

-- Waybar blur (input is enabled by default; no noinput rule needed)
hl.layer_rule({
    match = { namespace = "waybar" },
    blur = true,
})

-- =========================

-- Monitors

-- =========================

-- Primary monitor (ASUS, landscape)

hl.monitor({
    output   = "DP-1",
    mode     = "1920x1080@143.981",
    position = "0x0",
    scale    = 1,
})

-- Secondary monitor (MSI, portrait)

hl.monitor({
    output   = "DP-3",
    mode     = "preferred@60",
    position = "1920x0",
    scale    = 1,
    transform = 3,
})

-- Thunar darkmode

hl.env("GTK_THEME", "Adwaita-dark")

-- =========================

-- Autostart

-- =========================


-- Waybar


--


-- Idle daemon


-- =========================

-- Variables

-- =========================

local mainMod = "SUPER"

local terminal = "ghostty"

local fileManager = "thunar"

local menu = "wofi --show drun"

-- =========================

-- Input

-- =========================

hl.config({
    input = {
        kb_layout = "us",
        follow_mouse = 1,
        sensitivity = 0,
    },
})

-- =========================

-- Layout

-- =========================

hl.config({
    general = {
        layout = "master",
    },
})

hl.config({
    master = {
        new_status = "slave",
        new_on_top = 1,
        mfact = 0.70,
        orientation = "top",
    },
})

-- =========================

-- Workspace -> Monitor pinning (canonical)

-- =========================

-- Main monitor canonical workspaces

hl.workspace_rule({
    workspace = 1,
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = 2,
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = 3,
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = 6,
    monitor = "DP-1",
})

-- Secondary monitor canonical workspaces

hl.workspace_rule({
    workspace = 4,
    monitor = "DP-3",
})

hl.workspace_rule({
    workspace = 5,
    monitor = "DP-3",
})

-- Note: 7/8/9/10 intentionally NOT pinned (your "anarchy" spaces)

-- =========================

-- Keybindings

-- =========================

-- Theme Switcher

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "T", hl.dsp.exec_cmd("~/.config/hypr/scripts/theme-switcher.sh"))

-- Launchers

hl.bind(mainMod .. " + " .. "Q", hl.dsp.exec_cmd("ghostty"))

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("thunar"))

hl.bind(mainMod .. " + " .. "R", hl.dsp.exec_cmd("wofi --show drun"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "R", hl.dsp.exec_cmd("hyprctl reload"))

hl.bind(mainMod .. " + " .. "O", hl.dsp.exec_cmd("obsidian"))

hl.bind(mainMod .. " + " .. "Z", hl.dsp.exec_cmd("zen-browser"))

hl.bind(mainMod .. " + " .. "P", hl.dsp.exec_cmd("keepassxc"))

hl.bind(mainMod .. " + " .. "D", hl.dsp.exec_cmd("vesktop"))

-- Actions

hl.bind(mainMod .. " + " .. "C", hl.dsp.window.close())

-- Smart app scripts

hl.bind(mainMod .. " + " .. "S", hl.dsp.exec_cmd("~/.config/hypr/scripts/spotify-smart.sh"))

-- Lock / Sleep

hl.bind(mainMod .. " + " .. "L", hl.dsp.exec_cmd("hyprlock"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Escape", hl.dsp.exec_cmd("systemctl suspend"))

-- Screenshots

hl.bind("CTRL+SHIFT" .. " + " .. "S", hl.dsp.exec_cmd([[grim -g "$(slurp)" - | wl-copy]]))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.exec_cmd("grim ~/Images/Screenshots/screenshot-$(date +%F-%T).png"))

-- Focus movement (vim keys)

hl.bind(mainMod .. " + " .. "H", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "L", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "K", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "J", hl.dsp.focus({ direction = "down" }))

-- Workspaces (1-9, 0->10)

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Scroll workspaces

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Super + drag move/resize

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- =========================

-- Window rules (2026 Syntax)

-- =========================

-- General defaults

hl.window_rule({
    match = { class = ".*" },
    suppress_event = "maximize",
})

hl.window_rule({
    match = { class = "^$", title = "^$", xwayland = true },
    no_focus = true,
})

-- --- Workspace 1: Ghostty (dev terminal)

hl.window_rule({
    match = { class = "^(com\\.mitchellh\\.ghostty)$" },
    workspace = 1,
})

-- --- Workspace 4: Browser + AI

hl.window_rule({
    match = { class = "^(zen)$" },
    workspace = "4 silent",
})

hl.window_rule({
    match = { class = "^(firefox)$", title = ".*(ChatGPT|OpenAI).*" },
    workspace = "4 silent",
})

-- --- Workspace 5: Services (Discord, Steam, Spotify)

hl.window_rule({
    match = { class = "^(vesktop)$" },
    workspace = "5 silent",
})

hl.window_rule({
    match = { class = "^(steam)$" },
    workspace = "5 silent",
})

hl.window_rule({
    match = { class = "^(spotify)$" },
    workspace = "5 silent",
})

-- Steam games -> force to primary monitor (DP-1), workspace 3, confine pointer

hl.window_rule({
    match = { class = "^(steam_app_.*)$" },
    monitor = "DP-1",
})

hl.window_rule({
    match = { class = "^(steam_app_.*)$" },
    workspace = 3,
})

hl.window_rule({
    match = { class = "^(steam_app_.*)$" },
    confine_pointer = true,
})

hl.window_rule({
    match = { class = "^(feh)$" },
    float = true,
})

hl.window_rule({
    match = { class = "^(feh)$" },
    size = "800 600",
})

hl.window_rule({
    match = { class = "^(feh)$" },
    move = "100%-820 50",
})

-- Any Gamescope game goes to workspace 3

hl.window_rule({
    match = { class = "^(gamescope)$" },
    workspace = 3,
})

-- Media keys / DOIO knob

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("/home/hedgeknight/.config/hypr/start_wallpaper.sh")
    hl.exec_cmd("waybar")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("hypridle")
end)
