-- Generated by hyprconf2lua v1.3.2
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- --- Minimal Theme ---

hl.config({
    general = {
        gaps_in = 0,
        gaps_out = 0,
        border_size = 1,
        col = {
            active_border = "rgba(595959aa)",
        },
    },
})

hl.config({
    decoration = {
        rounding = 0,
        shadow = {
            enabled = false,
        },
    },
})

hl.config({
    animations = {
        enabled = false,
    },
})
